In [2]:
#Importamos las librerias pandas, numpy y matplotlib respectivamente
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Carga desde un archivo .csv sin indice
data = pd.read_csv('pais_filtrado.csv')
data.head(5)

,id,host_id,instant_bookable,latitude,longitude,property_type,room_type,accommodates,bathrooms,bedrooms,...,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,reviews_per_month,estimated_occupancy_l365d,estimated_revenue_l365d
0,27966.0,120502,t,35.33012,25.08012,Entire rental unit,Entire home/apt,3,1.5,1.0,...,4.92,4.94,4.91,4.96,4.99,4.64,4.92,0.82,48,2352.0
1,29856.0,128653,t,34.99533,24.75654,Private room in bed and breakfast,Private room,4,1.0,1.0,...,4.02,4.14,4.49,4.33,4.43,4.50,4.18,0.26,6,432.0
2,31023.0,133208,f,35.51439,24.01793,Entire rental unit,Entire home/apt,2,NaN,1.0,...,4.59,4.71,4.67,4.87,4.84,4.94,4.66,2.12,168,NaN
3,31789.0,136649,f,35.49648,23.69648,Entire rental unit,Entire home/apt,6,1.0,1.0,...,5.00,4.50,5.00,5.00,4.50,4.00,4.50,0.01,0,0.0
4,34280.0,147711,t,35.39616,25.02541,Entire rental unit,Entire home/apt,2,1.0,1.0,...,4.81,4.87,4.80,4.92,4.94,4.68,4.88,0.98,100,7000.0

In [4]:
#Identificar valores nulos por columna
valores_nulos= data.isnull().sum()
valores_nulos

id                                0
host_id                           0
instant_bookable                  0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                      2846
bedrooms                        257
beds                           2853
amenities                         0
bathrooms_text                   22
host_name                         1
host_since                        1
host_location                  8365
host_response_time             5821
host_response_rate             5821
host_acceptance_rate           2484
host_is_superhost               844
host_listings_count               1
host_total_listings_count         1
host_has_profile_pic              1
host_identity_verified            1
price                          2849
minimum_nights                    0
maximum_nights                    0
minimum_minimum_nights            0
maximum_minimum_nights            0
minimum_maximum_nights            0
maximum_maximum_nights            0
has_availability                823
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
number_of_reviews_ly              0
review_scores_rating           5698
review_scores_accuracy         5700
review_scores_cleanliness      5701
review_scores_checkin          5700
review_scores_communication    5700
review_scores_location         5700
review_scores_value            5700
reviews_per_month              5698
estimated_occupancy_l365d         0
estimated_revenue_l365d        2849
dtype: int64

In [5]:
#Identificar valores nulos por dataframe
valores_nulos=data.isnull().sum().sum()
valores_nulos

np.int64(81437)

In [6]:
#Realizamos una copia del dataframe
data1 = data.copy()

In [7]:
#BATHROOMS 
# #Primer mÃ©todo de sustituciÃ³n de valores nulos
#Sustituir valores nulos con promedio o media
data1["bathrooms"]=data1["bathrooms"].fillna(round(data["bathrooms"].mean(),1))

In [8]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

id                                0
host_id                           0
instant_bookable                  0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bedrooms                        257
beds                           2853
amenities                         0
bathrooms_text                   22
host_name                         1
host_since                        1
host_location                  8365
host_response_time             5821
host_response_rate             5821
host_acceptance_rate           2484
host_is_superhost               844
host_listings_count               1
host_total_listings_count         1
host_has_profile_pic              1
host_identity_verified            1
price                          2849
minimum_nights                    0
maximum_nights                    0
minimum_minimum_nights            0
maximum_minimum_nights            0
minimum_maximum_nights            0
maximum_maximum_nights            0
has_availability                823
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
number_of_reviews_ly              0
review_scores_rating           5698
review_scores_accuracy         5700
review_scores_cleanliness      5701
review_scores_checkin          5700
review_scores_communication    5700
review_scores_location         5700
review_scores_value            5700
reviews_per_month              5698
estimated_occupancy_l365d         0
estimated_revenue_l365d        2849
dtype: int64

In [9]:
#BEDROOMS 
#Sustituir valores nulos por valores no nulos hacia atrÃ¡s backward fill" ("bfill")
data1["bedrooms"] =data1["bedrooms"].fillna(method="bfill")

C:\Users\sammm\AppData\Local\Temp\ipykernel_7196\3652707435.py:3: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["bedrooms"] =data1["bedrooms"].fillna(method="bfill")

In [10]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

id                                0
host_id                           0
instant_bookable                  0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bedrooms                          0
beds                           2853
amenities                         0
bathrooms_text                   22
host_name                         1
host_since                        1
host_location                  8365
host_response_time             5821
host_response_rate             5821
host_acceptance_rate           2484
host_is_superhost               844
host_listings_count               1
host_total_listings_count         1
host_has_profile_pic              1
host_identity_verified            1
price                          2849
minimum_nights                    0
maximum_nights                    0
minimum_minimum_nights            0
maximum_minimum_nights            0
minimum_maximum_nights            0
maximum_maximum_nights            0
has_availability                823
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
number_of_reviews_ly              0
review_scores_rating           5698
review_scores_accuracy         5700
review_scores_cleanliness      5701
review_scores_checkin          5700
review_scores_communication    5700
review_scores_location         5700
review_scores_value            5700
reviews_per_month              5698
estimated_occupancy_l365d         0
estimated_revenue_l365d        2849
dtype: int64

In [11]:
#BEDS
#Sustituir valores nulos por valores no nulos hacia adelante forward fill" ("ffill")
#Filtro por columnas
data1["beds"] =data1["beds"].fillna(method="ffill")

C:\Users\sammm\AppData\Local\Temp\ipykernel_7196\4104927649.py:4: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data1["beds"] =data1["beds"].fillna(method="ffill")

In [12]:
#Corroboramos valores nulos
valores_nulos=data1.isnull().sum()
valores_nulos

id                                0
host_id                           0
instant_bookable                  0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bedrooms                          0
beds                              0
amenities                         0
bathrooms_text                   22
host_name                         1
host_since                        1
host_location                  8365
host_response_time             5821
host_response_rate             5821
host_acceptance_rate           2484
host_is_superhost               844
host_listings_count               1
host_total_listings_count         1
host_has_profile_pic              1
host_identity_verified            1
price                          2849
minimum_nights                    0
maximum_nights                    0
minimum_minimum_nights            0
maximum_minimum_nights            0
minimum_maximum_nights            0
maximum_maximum_nights            0
has_availability                823
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
number_of_reviews_ly              0
review_scores_rating           5698
review_scores_accuracy         5700
review_scores_cleanliness      5701
review_scores_checkin          5700
review_scores_communication    5700
review_scores_location         5700
review_scores_value            5700
reviews_per_month              5698
estimated_occupancy_l365d         0
estimated_revenue_l365d        2849
dtype: int64

In [ ]:
#BATHROOMS TEXT